#!/usr/bin/env ansible-playbook

- hosts: localhost
  become: yes

  pre_tasks:

  - name: Prozentsatz der Akkuladung anzeigen
    community.general.dconf:
      key: "/org/gnome/desktop/interface/show-battery-percentage"
      value: "true"
      state: present



  # manually done

  # Settings
  #   Desktop/Dock
  #     [ ] Dock bis zu den Bildschirmrändern ausbreiten
  #     [x] Intelligentes Ausblenden
  #         Dock anzeigen: Alle Anzeigegeräte
  #     [x] Linker Bereich des Bildschirms
  #   Energie
  #     [ ] Bildschirm bei Inaktivität abdunkeln
  #         Bildschirm abschalten: Nie
  #     [x] Prozentsatz der Akkuladung anzeigen
  #   Maus udn Tastenfeld
  #     [x] Natürlicher Bildlauf
  #   Benutzer
  #     [x] Automatische Anmeldung
  #   Datum und Zeit
  #         Zeitformat: 24-Stunden
  #   Info
  #         Gerätename: ...

  # nextcloud client
  #   user: makerspace-gt
  #   sync /home/maker/Öffentlich


#     # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
#     - name: Update && Dist-Upgrade the OS via apt
#       ansible.builtin.package:
#         update_cache: yes
#         cache_valid_time: 86400 # 1 day
#         upgrade: dist
#         autoremove: yes
#         autoclean: yes

#     # https://mutschler.eu/linux/install-guides/pop-os-post-install/

#     - name: Update Firmware
#       ansible.builtin.command: |
#         fwupdmgr get-devices -y &&
#         fwupdmgr get-updates &&
#         fwupdmgr update

#   roles:
#     # - role: ngetchell.vscode
#     # - role: ngetchell.vscode
#     #   vars:
#     #     become_user: "{{ user }}"
#     #     vscode_install: false
#     #     vscode_extension:
#     #       - platformio.platformio-ide
#     #       - cweijan.vscode-office
#     #       - robole.marky-stats
#     #       - yzhang.markdown-all-in-one
#     #       - ms-vsliveshare.vsliveshare-pack
#     #       - mhutchie.git-graph
#     - role: etcher

  tasks:

    - name: Install flatpak
      ansible.builtin.package:
        name: flatpak
        state: present

    - name: Add the flathub flatpak repository remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    ## Roles ##

    - name: Install VSCodium from flathub
      community.general.flatpak:
        name: com.vscodium.codium
        state: present


    ## CAD/CAM Programs ##

    - name: Install Prusa Slicer from flathub
      community.general.flatpak:
        name: com.prusa3d.PrusaSlicer
        state: present

    - name: Install FreeCAD from flathub
      community.general.flatpak:
        name: org.freecadweb.FreeCAD
        state: present

    - name: Install Blender from flathub
      community.general.flatpak:
        name: org.blender.Blender
        state: present

    - name: Install OpenSCAD from flathub
      community.general.flatpak:
        name: org.openscad.OpenSCAD
        state: present

    - name: Install GIMP from flathub
      community.general.flatpak:
        name: org.gimp.GIMP
        state: present

    - name: Install Inkscape from flathub
      community.general.flatpak:
        name: org.inkscape.Inkscape
        state: present

    - name: Install KiCad from flathub
      community.general.flatpak:
        name: org.kicad.KiCad
        state: present

#     - name: Install Printrun via generic OS package manager
#       ansible.builtin.package:
#         name: printrun

    - name: Install Scribus from flathub
      community.general.flatpak:
        name: net.scribus.Scribus
        state: present

    - name: Install Shotcut from flathub
      community.general.flatpak:
        name: org.shotcut.Shotcut
        state: present

#     - name: Install Darktable via generic OS package manager
#       ansible.builtin.package:
#         name: darktable

    - name: Install Sweet Home 3D from flathub
      community.general.flatpak:
        name: com.sweethome3d.Sweethome3d
        state: present

    - name: Install GNU Octave from flathub
      community.general.flatpak:
        name: org.octave.Octave
        state: present

#     - name: Install LibreCAD via generic OS package manager
#       ansible.builtin.package:
#         name: librecad

    - name: Install LeoCAD from flathub
      community.general.flatpak:
        name: org.leocad.LeoCAD
        state: present

    - name: Install MeshLab from flathub
      community.general.flatpak:
        name: net.meshlab.MeshLab
        state: present

    - name: Create LightBurn directory
      ansible.builtin.file:
        path: /opt/lightburn
        state: directory
        mode: '0777'
    - name: Download LightBurn
      get_url:
        url: https://github.com/LightBurnSoftware/deployment/releases/download/1.1.04/LightBurn-Linux64-v1.1.04.run
        dest: /opt/lightburn/LightBurn-Linux64.run
        mode: '0777'
    - name: Install LightBurn
      ansible.builtin.command: /opt/lightburn/LightBurn-Linux64.run --nox11

#     ## Backup Programs ##

    # - name: Install  from flathub
    #   community.general.flatpak:
    #     name: 
    #     state: present

#     - name: Install Syncthing via generic OS package manager
#       ansible.builtin.package:
#         name: syncthing

#     - name: Install KeePassXC via generic OS package manager
#       ansible.builtin.package:
#         name: keepassxc

#     - name: Install Nextcloud Desktop via generic OS package manager
#       ansible.builtin.package:
#         name: nextcloud-desktop

    - name: Install rsync via generic OS package manager
      ansible.builtin.package:
        name:
          - rsync
          - grsync
        state: present

#     ## Writing Programs ##

    - name: Install Pandoc via generic OS package manager
      ansible.builtin.package:
        name:
          - pandoc
          # - pandoc-citeproc
        state: present

    - name: Install TeX Live via generic OS package manager
      ansible.builtin.package:
        name:
          - texlive
          # - texlive-lang-german
          # - texlive-latex-extra
          # - texlive-fonts-extra
          # - texlive-luatex
        state: present

    - name: Install Calibre via generic OS package manager
      ansible.builtin.package:
        name: calibre

    - name: Install AsciiDoc via generic OS package manager
      ansible.builtin.package:
        name: asciidoc

    - name: Install pdfgrep via generic OS package manager
      ansible.builtin.package:
        name: pdfgrep


#     ## Coding Programs ##

    # - name: Install Vagrant via generic OS package manager
    #   ansible.builtin.package:
    #     name:
    #       - vagrant
    #       - virtualbox

    # - name: Install QEMU via generic OS package manager
    #   ansible.builtin.package:
    #     name:
    #       - qemu
    #       - qemu-user-static
    #       - binfmt-support

#     - name: Install Arduino IDE via generic OS package manager
#       ansible.builtin.package:
#         name: arduino

    - name: Install Android Tools via generic OS package manager
      ansible.builtin.package:
        name:
          - adb
          - fastboot

    - name: Install git via generic OS package manager
      ansible.builtin.package:
        name:
          - git
          - git-lfs

    - name: Install Subversion via generic OS package manager
      ansible.builtin.package:
        name:
          - subversion
          - git-svn

#     - name: Install Node.js via generic OS package manager
#       ansible.builtin.package:
#         name:
#           - nodejs
#           - npm


#     ## Media Programs ##

#     - name: Install VLC media player via generic OS package manager
#       ansible.builtin.package:
#         name:
#           - vlc
#           - gstreamer1.0-libav

#     - name: Install Audacity via generic OS package manager
#       ansible.builtin.package:
#         name: audacity

#     - name: Install Ardour via generic OS package manager
#       ansible.builtin.package:
#         name: ardour

#     - name: Install OBS Studio via generic OS package manager
#       ansible.builtin.package:
#         name:
#           - obs-studio
#           - v4l2loopback-dkms

#     - name: Install Cheese via generic OS package manager
#       ansible.builtin.package:
#         name: cheese


#     ## Communications Programs ##

#     - name: Install Discord via generic OS package manager
#       ansible.builtin.package:
#         name: discord

#     - name: install zoom
#       ansible.builtin.package:
#         deb: https://zoom.us/client/latest/zoom_amd64.deb


#     ## Learning Programs ##

#     - name: Install Anki via generic OS package manager
#       ansible.builtin.package:
#         name: anki

#     - name: Install Pomodoro via generic OS package manager
#       ansible.builtin.package:
#         name: gnome-shell-pomodoro
#       # needs shell extension for top bar
#       # https://extensions.gnome.org/extension/53/pomodoro/


#     ## Finance Programs ##

#     - name: Install GnuCash via generic OS package manager
#       ansible.builtin.package:
#         name: gnucash


#     ## Web Programs ##

#     - name: Install Chromium via generic OS package manager
#       ansible.builtin.package:
#         name: chromium-browser

#     - name: Install Transmission via generic OS package manager
#       ansible.builtin.package:
#         name: transmission

#     - name: Install TIPP10 via generic OS package manager
#       ansible.builtin.package:
#         name: tipp10

#     - name: Install Nmap via generic OS package manager
#       ansible.builtin.package:
#         name: nmap

#     - name: Install Remmina via generic OS package manager
#       ansible.builtin.package:
#         name: remmina


#     ## CLI Programs ##

    - name: Install acpi via generic OS package manager
      ansible.builtin.package:
        name: acpi

    - name: Install ncdu via generic OS package manager
      ansible.builtin.package:
        name: ncdu

    - name: Install tlp via generic OS package manager
      ansible.builtin.package:
        name: tlp

    - name: Install tree via generic OS package manager
      ansible.builtin.package:
        name: tree

    - name: Install vim via generic OS package manager
      ansible.builtin.package:
        name: vim

    - name: Install powertop via generic OS package manager
      ansible.builtin.package:
        name: powertop

    - name: Install traceroute via generic OS package manager
      ansible.builtin.package:
        name: traceroute

    - name: Install htop via generic OS package manager
      ansible.builtin.package:
        name: htop

    - name: Install neofetch via generic OS package manager
      ansible.builtin.package:
        name: neofetch

    # - name: Install hw-probe via generic OS package manager
    #   ansible.builtin.package:
    #     name: hw-probe

    - name: Install whois via generic OS package manager
      ansible.builtin.package:
        name: whois

#   #config Programs

#     - name: Install Tweaks via generic OS package manager
#       ansible.builtin.package:
#         name: gnome-tweak-tool

# # deepnest
# # inkstitch
# # davinci resolve
# # https://support.system76.com/articles/install-davinci-resolve

# # common
# # user
# # veracrypt
# # element
# # zotero
# # typora
# # xournal++
# # parsec
# # among us
# # minecraft
# # table top simulator
# # linphone / sip client
# # implicitcad
# # bitwarden
# # teamviewer
# # unattended-upgraded / apt-listchanges
# # wireguard
# # https://extensions.gnome.org/extension/906/sound-output-device-chooser/
# # https://extensions.gnome.org/extension/3396/color-picker/
